import Head from 'next/head';

import ComponentBoilerplate from '@/components/component-boilerplate';

export default function Home() {
  return (
    <>
      <Head>
        <title>Front-end Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ComponentBoilerplate />
    </>
  );
}
